// src/constants/index.js - Export centralisé de toutes les constantes

// ================================
// FIELD MAPPINGS (nouveau)
// ================================
export { 
  ALL_MAPPINGS, 
  CONTEXT_MAPPINGS, 
  initializeFieldMappings,
  getMappingsForContext,
  validateMappings,
  addCustomMappings
} from './fieldMappings';

// ================================
// TARIFICATION
// ================================
export { 
  FORM_MODES as TARIF_FORM_MODES,
  FORM_TYPES,
  FORM_TITLES as TARIF_FORM_TITLES,
  LOADING_MESSAGES as TARIF_LOADING_MESSAGES,
  VALIDATION_MESSAGES as TARIF_VALIDATION_MESSAGES,
  ACTION_TYPES as TARIF_ACTION_TYPES,
  NOTIFICATION_TYPES as TARIF_NOTIFICATION_TYPES
} from './tarifConstants';

// ================================
// FACTURATION
// ================================
export { 
  FORM_MODES as FACTURE_FORM_MODES,
  VALIDATION_MESSAGES as FACTURE_VALIDATION_MESSAGES,
  BUTTON_TEXTS as FACTURE_BUTTON_TEXTS,
  FORM_TITLES as FACTURE_FORM_TITLES
} from './factureConstants';

// ================================
// PAIEMENTS
// ================================
export { 
  PAIEMENT_ETATS,
  METHODES_PAIEMENT,
  METHODES_PAIEMENT_LABELS,
  VALIDATION_MESSAGES as PAIEMENT_VALIDATION_MESSAGES,
  BUTTON_TEXTS as PAIEMENT_BUTTON_TEXTS,
  FORM_TITLES as PAIEMENT_FORM_TITLES,
  SECTION_TITLES as PAIEMENT_SECTION_TITLES,
  LABELS as PAIEMENT_LABELS,
  PAIEMENT_DATE_CONFIG,
  LOG_ACTIONS as PAIEMENT_LOG_ACTIONS,
  NOTIFICATIONS as PAIEMENT_NOTIFICATIONS,
  LOADING_MESSAGES as PAIEMENT_LOADING_MESSAGES,
  HELP_TEXTS as PAIEMENT_HELP_TEXTS,
  LIMITS as PAIEMENT_LIMITS
} from './paiementConstants';

// ================================
// DATES
// ================================
export { 
  DATE_FORMATS,
  LOCALES,
  DATE_VALIDATION_MESSAGES,
  DATE_ERROR_MESSAGES,
  DATE_INFO_MESSAGES,
  DATE_LABELS,
  DATE_BUTTON_TEXTS,
  DATE_CONSTRAINTS,
  DATEPICKER_CONFIG,
  DATE_LOADING_MESSAGES,
  CONTEXT_CONFIGS as DATE_CONTEXT_CONFIGS,
  DATE_HELPERS,
  VALIDATION_TYPES as DATE_VALIDATION_TYPES
} from './dateConstants';

// ================================
// EXPORTS GROUPÉS PAR DOMAINE
// ================================

// Groupe tarification
export const TARIFICATION = {
  FORM_MODES: TARIF_FORM_MODES,
  FORM_TYPES,
  FORM_TITLES: TARIF_FORM_TITLES,
  LOADING_MESSAGES: TARIF_LOADING_MESSAGES,
  VALIDATION_MESSAGES: TARIF_VALIDATION_MESSAGES,
  ACTION_TYPES: TARIF_ACTION_TYPES,
  NOTIFICATION_TYPES: TARIF_NOTIFICATION_TYPES
};

// Groupe facturation  
export const FACTURATION = {
  FORM_MODES: FACTURE_FORM_MODES,
  VALIDATION_MESSAGES: FACTURE_VALIDATION_MESSAGES,
  BUTTON_TEXTS: FACTURE_BUTTON_TEXTS,
  FORM_TITLES: FACTURE_FORM_TITLES
};

// Groupe dates
export const DATES = {
  FORMATS: DATE_FORMATS,
  LOCALES,
  VALIDATION_MESSAGES: DATE_VALIDATION_MESSAGES,
  ERROR_MESSAGES: DATE_ERROR_MESSAGES,
  INFO_MESSAGES: DATE_INFO_MESSAGES,
  LABELS: DATE_LABELS,
  BUTTON_TEXTS: DATE_BUTTON_TEXTS,
  CONSTRAINTS: DATE_CONSTRAINTS,
  DATEPICKER_CONFIG,
  LOADING_MESSAGES: DATE_LOADING_MESSAGES,
  CONTEXT_CONFIGS: DATE_CONTEXT_CONFIGS,
  HELPERS: DATE_HELPERS,
  VALIDATION_TYPES: DATE_VALIDATION_TYPES
};

// Groupe paiements
export const PAIEMENTS = {
  ETATS: PAIEMENT_ETATS,
  METHODES: METHODES_PAIEMENT,
  METHODES_LABELS: METHODES_PAIEMENT_LABELS,
  VALIDATION_MESSAGES: PAIEMENT_VALIDATION_MESSAGES,
  BUTTON_TEXTS: PAIEMENT_BUTTON_TEXTS,
  FORM_TITLES: PAIEMENT_FORM_TITLES,
  SECTION_TITLES: PAIEMENT_SECTION_TITLES,
  LABELS: PAIEMENT_LABELS,
  DATE_CONFIG: PAIEMENT_DATE_CONFIG,
  LOG_ACTIONS: PAIEMENT_LOG_ACTIONS,
  NOTIFICATIONS: PAIEMENT_NOTIFICATIONS,
  LOADING_MESSAGES: PAIEMENT_LOADING_MESSAGES,
  HELP_TEXTS: PAIEMENT_HELP_TEXTS,
  LIMITS: PAIEMENT_LIMITS
};

// Groupe field mappings
export const FIELD_MAPPINGS = {
  ALL: ALL_MAPPINGS,
  CONTEXTS: CONTEXT_MAPPINGS,
  initialize: initializeFieldMappings,
  getForContext: getMappingsForContext,
  validate: validateMappings,
  addCustom: addCustomMappings
};

// ================================
// EXPORT PAR DÉFAUT POUR USAGE GLOBAL
// ================================
export default {
  TARIFICATION,
  FACTURATION,
  DATES,
  PAIEMENTS,
  FIELD_MAPPINGS
};